# Generated by Django 6.0.5 on 2026-05-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_module_topic_presentation_topicimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='presentations/'),
        ),
        migrations.AlterField(
            model_name='topicimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topic_images/'),
        ),
    ]
