# Generated by Django 6.0.5 on 2026-05-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_presentation_file_alter_topicimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Помощник')], max_length=16)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сообщение помощника',
                'verbose_name_plural': 'Сообщения помощника',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Презентация', 'verbose_name_plural': 'Презентации'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterModelOptions(
            name='topicimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Изображение темы', 'verbose_name_plural': 'Изображения тем'},
        ),
    ]
